Repository funniture-Project/funniture-fe, pull requests merged in 2025-03, with the labels that each got.

#205 :globe_with_meridians:[PR]2025/03/01 사용자별 주문 조회 페이징 처리 적용 (프론트&백 연결) - 정은미:globe_with_meridians:
  funniture-fe/src/apis/RentalAPI.js
  funniture-fe/src/component/Pagination.js
  funniture-fe/src/pages/user/Orders.js
  funniture-fe/src/pages/user/orders.module.css
Labels: 🔨Refactor🔨

#206 :globe_with_meridians:[PR]2025/03/01 관리자 예약정보 조회 페이징 처리 적용(프론트&백 연결) - 정은미:globe_with_meridians:
  funniture-fe/src/apis/RentalAPI.js
  funniture-fe/src/pages/admin/Rental.js
  funniture-fe/src/pages/admin/rental.module.css
  funniture-fe/src/pages/owner/ownerRental.module.css
Labels: 🔨Refactor🔨, ✨Feature✨, 🎨CSS🎨

#209 🌐✨[PR]2025/03/02 제공자 전환 신청 반려 / 승인 - 김규남✨🌐
  funniture-fe/src/apis/AdminAPI.js
  funniture-fe/src/component/BtnModal.js
  funniture-fe/src/pages/admin/AdminConvert.js
Labels: ✨Feature✨, 📅ToDo📅

#210 :globe_with_meridians:[PR]2025/03/02 제공자 주문번호 클릭 시 예약 상세정보 출력 - 정은미:globe_with_meridians:
  funniture-fe/src/pages/owner/OwnerRental.js
  funniture-fe/src/pages/user/DetailOrder.js
  funniture-fe/src/pages/user/detailorder.module.css
Labels: ✨Feature✨

#212 :globe_with_meridians:[PR]2025/03/02 주문 상세페이지 사용자, 제공자 각각 데이터 구분 - 정은미:globe_with_meridians:
  funniture-fe/src/pages/user/DetailOrder.js
  funniture-fe/src/pages/user/detailorder.module.css
Labels: 🔨Refactor🔨

#213 🌐✨[PR]2025/03/02 제공자 전환 신청 후, 심사 텍스트 출력 및 기타 로직 -김규남 ✨🌐
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/pages/user/AppConvert.js
  funniture-fe/src/pages/user/SubmissionMessage.js
  funniture-fe/src/pages/user/submissionMessage.module.css
Labels: 🔨Refactor🔨, 📅ToDo📅, 🎨CSS🎨

#215 :lipstick:[PR]2025/03/03 전체&예약탭에서만 예약취소, 예약확정 버튼 보이게하기 - 정은미:lipstick:
  funniture-fe/src/pages/owner/OwnerRental.js
  funniture-fe/src/pages/owner/ownerRental.module.css
Labels: 🎨CSS🎨

#217 :globe_with_meridians:[PR]2025/03/03 다중선택하여 예약확정 백&프론트 연결 - 정은미:globe_with_meridians:
  funniture-fe/src/apis/RentalAPI.js
  funniture-fe/src/pages/owner/OwnerRental.js
Labels: ✨Feature✨

#224 ✨[PR] 2025/03/01 ~ 2025/03/02 챗봇 연결 및 favorite 오류해결 - 정예진 🐛
  funniture-fe/src/App.js
  funniture-fe/src/apis/ChatAPI.js
  funniture-fe/src/assets/images/nofound_1.jpg
  funniture-fe/src/assets/images/notfound_2.jpg
  funniture-fe/src/assets/images/white_chiar_logo.png
  funniture-fe/src/assets/images/white_logo.png
  funniture-fe/src/component/ChatModal.js
  funniture-fe/src/component/ChatModal.module.css
  funniture-fe/src/component/TopDownBtn.js
  funniture-fe/src/component/topdownbtn.module.css
  funniture-fe/src/layouts/LoginRouter.js
  funniture-fe/src/layouts/UserRouter.js
  funniture-fe/src/pages/common/ListPage.js
  funniture-fe/src/pages/common/NotFoundPage.js
  funniture-fe/src/pages/common/ProductDetailPage.js
  funniture-fe/src/pages/common/notFoundPage.module.css
  funniture-fe/src/pages/login/Login.js
  funniture-fe/src/pages/user/FavoritesPage.js
  funniture-fe/src/pages/user/Recentproduct.js
  funniture-fe/src/redux/modules/ChatModule.js
  funniture-fe/src/redux/modules/index.js
Labels: 🔨Refactor🔨, ✨Feature✨, 📅ToDo📅, ✅PR✅, 🎨CSS🎨

#226 :lipstick:[PR]2025/03/03 제공자 마이페이지 주문번호 클릭 -> 주문상세 구조 변경 CSS - 정은미:lipstick:
  funniture-fe/src/pages/owner/OwnerRental.js
  funniture-fe/src/pages/owner/ownerRental.module.css
  funniture-fe/src/pages/user/DetailOrder.js
  funniture-fe/src/pages/user/detailorder.module.css
Labels: 🎨CSS🎨

#228 🌐✨[PR]2025/03/03 제공자 전환 신청 / 반려 메시지 / 재신청 연결 - 김규남✨🌐
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/pages/admin/AdminConvert.js
  funniture-fe/src/pages/user/AppConvert.js
  funniture-fe/src/pages/user/SubmissionMessage.js
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅

#229 :sparkles:[PR]2025/03/03 예약 대기 -> 예약 취소로 상태 백&프론트 연결 - 정은미:sparkles:
  funniture-fe/src/apis/RentalAPI.js
  funniture-fe/src/pages/owner/OwnerRental.js
  funniture-fe/src/pages/user/DetailOrder.js
Labels: ✨Feature✨

#230 :lipstick:[PR]2025/03/03 운송장, 택배사 더블클릭 -> 운송장 등록모달 CSS - 정은미:lipstick:
  funniture-fe/src/pages/owner/DeliverComModal.js
  funniture-fe/src/pages/owner/OwnerRental.js
  funniture-fe/src/pages/owner/deliverComModal.module.css
Labels: 🎨CSS🎨

#233 :globe_with_meridians:[PR]2025/03/03 운송장 등록 백&프론트 연결:globe_with_meridians:
  funniture-fe/src/apis/RentalAPI.js
  funniture-fe/src/pages/owner/DeliverComModal.js
  funniture-fe/src/pages/owner/OwnerRental.js
  funniture-fe/src/pages/owner/deliverComModal.module.css
Labels: ✨Feature✨

#234 ✨[PR]2025/03/03 관리자 페이지 상세 정보 / 전체 체크 / 데이터 이동 - 김규남 ✨
  funniture-fe/src/apis/AdminAPI.js
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/pages/admin/AdminLeaver.js
  funniture-fe/src/pages/admin/AdminOwner.js
  funniture-fe/src/pages/admin/AdminUser.js
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅

#237 [PR]2025/03/04 모달 바디 수정 - 김규남
  funniture-fe/src/component/BtnModal.js
Labels: 🚫Error🚫, 🔨Refactor🔨

#239 :globe_with_meridians:[PR]2025/03/04 memberId 고정 값 로그인 유저 값으로 변경 - 정은미:globe_with_meridians:
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/pages/owner/OwnerRental.js
  funniture-fe/src/pages/user/Orders.js
  funniture-fe/src/pages/user/RentalRegist.js
Labels: 🔨Refactor🔨

#245 :lipstick: [PR] 2025/03/04 관리자 문의 관리 페이지 - 정예진 :lipstick:
  funniture-fe/src/App.js
  funniture-fe/src/assets/icon/minus-solid.svg
  funniture-fe/src/assets/images/default.jpg
  funniture-fe/src/component/BtnModal.js
  funniture-fe/src/component/ChatModal.js
  funniture-fe/src/pages/admin/AdminConvert.js
  funniture-fe/src/pages/admin/AdminQnAPage.js
  funniture-fe/src/pages/admin/AdminQnAPage.module.css
  funniture-fe/src/pages/common/ListPage.js
  funniture-fe/src/pages/common/NotFoundPage.js
  funniture-fe/src/pages/common/ProductDetailPage.js
  funniture-fe/src/pages/common/productDetail.module.css
  funniture-fe/src/pages/owner/OwnerProducts.js
  funniture-fe/src/pages/owner/OwnerRegister.js
  funniture-fe/src/pages/owner/OwnerRental.js
Labels: 🔨Refactor🔨, 📅ToDo📅, ✅PR✅, 🎨CSS🎨

#246 :sparkles: [PR] 2025/03/04 관리자 페이지 질문 관리 백 & 프론트 연결 - 정예진 :sparkles:
  funniture-fe/src/apis/ChatAPI.js
  funniture-fe/src/component/ChatModal.js
  funniture-fe/src/pages/admin/AdminQnAPage.js
  funniture-fe/src/pages/admin/AdminQnAPage.module.css
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅

#248 :lipstick:[PR]2025/03/04 모달 사이즈 제한하기 - 정은미:lipstick:
  funniture-fe/src/component/BtnModal.module.css
Labels: 🎨CSS🎨

#249 🐛✨[PR]2025/03/04 제공자 전환 유효성 검증 추가 - 김규남 ✨🐛
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/pages/user/AppConvert.js
Labels: 🔨Refactor🔨, 📅ToDo📅, 🎨CSS🎨

#251 :globe_with_meridians:[PR]2025/03/04 기본배송지로 변경, 배송지 삭제 백&프론트 연결 - 정은미:globe_with_meridians:
  funniture-fe/src/App.js
  funniture-fe/src/apis/DeliveryAddressAPI.js
  funniture-fe/src/assets/icon/circle-check-solid-brown.svg
  funniture-fe/src/assets/icon/circle-check-solid.svg
  funniture-fe/src/pages/user/DeliveryAddress.js
  funniture-fe/src/pages/user/MyPage.js
  funniture-fe/src/pages/user/deliveryAddress.module.css
Labels: ✨Feature✨

#253 :globe_with_meridians:[PR]2025/03/04 신규배송지 등록 백&프론트 연결 - 정은미:globe_with_meridians:
  funniture-fe/src/apis/DeliveryAddressAPI.js
  funniture-fe/src/pages/user/DeliveryAddress.js
  funniture-fe/src/pages/user/RentalRegist.js
Labels: ✨Feature✨

#256 :globe_with_meridians:[PR]2025/03/04 배송지 수정 -> 백&프론트 연결 - 정은미:globe_with_meridians:
  funniture-fe/src/apis/DeliveryAddressAPI.js
  funniture-fe/src/pages/user/DeliveryAddress.js
  funniture-fe/src/pages/user/deliveryAddress.module.css
Labels: ✨Feature✨

#255 💄✨[PR]2025/03/04 회원가입일 형식 변경 / 전체 모달 적용 - 김규남 ✨💄
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/component/Header.js
  funniture-fe/src/pages/admin/AdminConvert.js
  funniture-fe/src/pages/admin/AdminLeaver.js
  funniture-fe/src/pages/admin/AdminOwner.js
  funniture-fe/src/pages/admin/AdminUser.js
  funniture-fe/src/pages/login/Singup.js
  funniture-fe/src/pages/user/Convert.js
  funniture-fe/src/pages/user/SubmissionMessage.js
  funniture-fe/src/pages/user/submissionMessage.module.css
Labels: ✨Feature✨, 📅ToDo📅, 🎨CSS🎨

#263 :globe_with_meridians:[PR]2025/03/05 관리자페이지(예약정보) -> 대여자, 판매자정보 드롭다운 - 정은미:globe_with_meridians:
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/pages/admin/Rental.js
  funniture-fe/src/pages/admin/rental.module.css
Labels: ✨Feature✨

#265 :sparkles: [PR] 2025/03/05 관리자 페이지 챗봇 질문 관리 수정, 등록 완료 - 정예진 :sparkles:
  funniture-fe/src/apis/ChatAPI.js
  funniture-fe/src/component/BtnModal.js
  funniture-fe/src/component/ChatModal.js
  funniture-fe/src/component/ChatModal.module.css
  funniture-fe/src/component/Header.js
  funniture-fe/src/pages/admin/AdminManageChat.js
  funniture-fe/src/pages/admin/AdminQnAPage.js
  funniture-fe/src/pages/admin/AdminQnAPage.module.css
  funniture-fe/src/pages/admin/AdminmanageChat.module.css
  funniture-fe/src/pages/common/ProductDetailPage.js
  funniture-fe/src/pages/owner/OwnerRegister.js
  funniture-fe/src/redux/modules/ChatModule.js
  funniture-fe/src/redux/modules/MemberModule.js
Labels: 🔨Refactor🔨, ✨Feature✨, 📅ToDo📅, ✅PR✅

#266 :globe_with_meridians:[PR]2025/03/05 사용상품/반납 조회 - 백&프론트 연결 - 정은미:globe_with_meridians:
  funniture-fe/src/apis/RentalAPI.js
  funniture-fe/src/pages/owner/OwnerRental.js
  funniture-fe/src/pages/user/DeliveryAddress.js
  funniture-fe/src/pages/user/OrdersReturn.js
  funniture-fe/src/pages/user/deliveryAddress.module.css
  funniture-fe/src/pages/user/ordersReturn.module.css
Labels: ✨Feature✨

#267 🐛[PR]2025/03/05 제공자 전환 신청 / 관리자 페이지 페이징 수정 - 김규남 🐛
  funniture-fe/src/apis/AdminAPI.js
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/pages/admin/AdminConvert.js
  funniture-fe/src/pages/admin/AdminLeaver.js
  funniture-fe/src/pages/user/AppConvert.js
Labels: 🚫Error🚫, 🔨Refactor🔨, 📅ToDo📅

#269 ✨ [PR] 2025/03/05 챗봇 진행 오류 수정 및 질문 삭제 가능 - 정예진 ✨
  funniture-fe/src/apis/ChatAPI.js
  funniture-fe/src/component/ChatModal.js
  funniture-fe/src/pages/admin/AdminManageChat.js
Labels: 🔨Refactor🔨, ✨Feature✨, 📅ToDo📅, ✅PR✅

#270 :truck: [PR] 2025/03/05 페이지 연결용 -정예진 :truck:
  funniture-fe/src/component/ChatModal.js
  funniture-fe/src/component/ChatModal.module.css
  funniture-fe/src/pages/common/ProductDetailPage.js
Labels: 🎨CSS🎨

#274 🌐[PR]2025/03/05 상품 별 전체 문의 조회 연결 - 김규남🌐
  funniture-fe/src/App.js
  funniture-fe/src/apis/InquiryAPI.js
  funniture-fe/src/pages/common/Inquiry.js
  funniture-fe/src/pages/common/ProductDetailPage.js
  funniture-fe/src/pages/common/inquiryProduct.module.css
  funniture-fe/src/pages/user/Inquiry.js
  funniture-fe/src/pages/user/UserConform.js
Labels: 📅ToDo📅, ✅PR✅, 🎨CSS🎨

#276 :globe_with_meridians:[PR]2025/03/06 마이페이지 포인트 조회 - 정은미:globe_with_meridians:
  funniture-fe/src/apis/PointAPI.js
  funniture-fe/src/pages/user/MyPage.js
  funniture-fe/src/pages/user/mypage.css
Labels: ✨Feature✨

#279 :globe_with_meridians:[PR]2025/03/06 사용자 마이페이지 예약진행상태별 갯수 조회 - 정은미:globe_with_meridians:
  funniture-fe/src/apis/RentalAPI.js
  funniture-fe/src/pages/user/MyPage.js
  funniture-fe/src/pages/user/mypage.css
Labels: ✨Feature✨

#280 ✨[PR]2025/03/06 상품 문의 등록 연결 - 김규남 ✨
  funniture-fe/src/apis/InquiryAPI.js
  funniture-fe/src/pages/common/Inquiry.js
  funniture-fe/src/pages/common/inquiryProduct.module.css
Labels: ✨Feature✨, 📅ToDo📅

#282 :globe_with_meridians:[PR]2025/03/06 사용자 주문/배송 날짜 선택 필터링 - 정은미:globe_with_meridians:
  funniture-fe/src/apis/RentalAPI.js
  funniture-fe/src/pages/admin/Rental.js
  funniture-fe/src/pages/user/Orders.js
  funniture-fe/src/pages/user/orders.module.css
Labels: ✨Feature✨

#284 🌐✨[PR]2025/03/06 제공자 마이페이지 문의 연결 / 문의 작성 수정- 김규남✨🌐
  funniture-fe/src/App.js
  funniture-fe/src/apis/InquiryAPI.js
  funniture-fe/src/pages/common/Inquiry.js
  funniture-fe/src/pages/owner/OwnerInquiry.js
  funniture-fe/src/pages/owner/OwnerMyPage.js
  funniture-fe/src/pages/owner/ownerInquiry.module.css
  funniture-fe/src/pages/owner/ownermypage.module.css
Labels: 🔨Refactor🔨, ✨Feature✨, 📅ToDo📅, 🎨CSS🎨

#286 :globe_with_meridians:[PR]2025/03/06 사용자 주문 상세페이지 선택 배송지로 수정하기 - 정은미:globe_with_meridians:
  funniture-fe/src/apis/RentalAPI.js
  funniture-fe/src/pages/user/DeliveryAddressModal.js
  funniture-fe/src/pages/user/DetailOrder.js
  funniture-fe/src/pages/user/RentalRegist.js
  funniture-fe/src/pages/user/deliveryAddressModal.module.css
  funniture-fe/src/pages/user/detailorder.module.css
  funniture-fe/src/pages/user/orders.module.css
  funniture-fe/src/pages/user/rentalRegist.module.css
Labels: ✨Feature✨

#289 🌐✨[PR]2025/03/06 제공자 메인 페이지 문의 연결 / 문의 페이지 문의 연결 - 김규남✨🌐
  funniture-fe/src/apis/InquiryAPI.js
  funniture-fe/src/pages/owner/OwnerInquiry.js
  funniture-fe/src/pages/owner/OwnerMyPage.js
  funniture-fe/src/pages/owner/ownerInquiry.module.css
  funniture-fe/src/pages/owner/ownerMainInquiry.module.css
  funniture-fe/src/redux/modules/OwnerModule.js
  funniture-fe/src/redux/modules/index.js
Labels: ✨Feature✨, 📅ToDo📅, 🎨CSS🎨

#291 :lipstick: [PR] 2025/03/06 관리자 페이지 문의 관리 조회 연결 완료 -정예진 :lipstick:
  funniture-fe/src/apis/AdminInquiryAPI.js
  funniture-fe/src/assets/icon/important-icon.svg
  funniture-fe/src/assets/icon/send-icon.svg
  funniture-fe/src/pages/admin/AdminDirectPage.module.css
  funniture-fe/src/pages/admin/AdminQnAPage.js
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅, 🎨CSS🎨

#296 🌐✨[PR]2025/03/07 제공자 문의 페이지 페이징 처리 , 답변 여부에 따라 탭 구분 - 김규남✨🌐
  funniture-fe/src/apis/InquiryAPI.js
  funniture-fe/src/pages/owner/OwnerInquiry.js
  funniture-fe/src/pages/owner/OwnerMyPage.js
  funniture-fe/src/pages/owner/ownerInquiry.module.css
  funniture-fe/src/redux/modules/OwnerModule.js
Labels: ✨Feature✨, 📅ToDo📅, 🎨CSS🎨

#297 :globe_with_meridians:[PR]2025/03/07 사용자 반납요청 백&프론트 연결-정은미:globe_with_meridians:
  funniture-fe/src/apis/RentalAPI.js
  funniture-fe/src/pages/user/OrderReturnRegist.js
  funniture-fe/src/pages/user/OrdersReturn.js
Labels: ✨Feature✨

#299 🌐✨[PR]2025/03/07 사용자 마이페이지 문의 데이터 스토어 저장 - 김규남 ✨🌐
  funniture-fe/src/App.js
  funniture-fe/src/apis/InquiryAPI.js
  funniture-fe/src/pages/owner/OwnerInquiry.js
  funniture-fe/src/pages/user/MyPage.js
  funniture-fe/src/pages/user/UserInquiry.js
  funniture-fe/src/pages/user/mypageInquiry.module.css
  funniture-fe/src/redux/modules/MemberModule.js
Labels: 📅ToDo📅, 🎨CSS🎨

#300 :globe_with_meridians:[PR]2025/03/07 배송중 -> 배송완료 예약진행상태 수정(모달) - 정은미:globe_with_meridians:
  funniture-fe/src/pages/owner/DeliveryInProgressModal.js
  funniture-fe/src/pages/owner/OwnerRental.js
  funniture-fe/src/pages/owner/deliveryInProgressModal.module.css
  funniture-fe/src/pages/user/OrderReturnRegist.js
  funniture-fe/src/pages/user/OrdersReturn.js
Labels: ✨Feature✨

#303 :globe_with_meridians:[PR]2025/03/08 배송중에서 배송완료로 상태 변경&운송장 수정 - 정은미:globe_with_meridians:
  funniture-fe/src/pages/owner/DeliveryInProgressModal.js
  funniture-fe/src/pages/owner/OwnerRental.js
  funniture-fe/src/pages/owner/ownerRental.module.css
  funniture-fe/src/pages/user/RentalRegist.js
Labels: ✨Feature✨

#305 :globe_with_meridians:[PR]2025/03/08 예약 상태 변경(운송장 등록&반납요청->수거중, 수거중->반납완료) - 정은미:globe_with_meridians:
  funniture-fe/src/pages/owner/DeliveryInProgressModal.js
  funniture-fe/src/pages/owner/OwnerRental.js
Labels: ✨Feature✨

#307 🌐✨[PR]2025/03/08 사용자 페이지 문의 조회 연결 및 css - 김규남 ✨🌐
  funniture-fe/src/apis/InquiryAPI.js
  funniture-fe/src/pages/owner/OwnerInquiry.js
  funniture-fe/src/pages/user/UserInquiry.js
  funniture-fe/src/redux/modules/MemberModule.js
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅, 🎨CSS🎨

#309 🌐✨[PR]2025/03/08 사용자 리뷰 페이지 조회 -김규남 ✨🌐
  funniture-fe/src/App.js
  funniture-fe/src/apis/ReviewAPI.js
  funniture-fe/src/pages/user/MyPage.js
  funniture-fe/src/pages/user/UserReview.js
  funniture-fe/src/pages/user/mypagereview.module.css
  funniture-fe/src/redux/modules/MemberModule.js
Labels: ✨Feature✨, 📅ToDo📅, 🎨CSS🎨

#311 🌐✨[PR]2025/03/08 리뷰 데이터 제품 상세페이지 연결 - 김규남 ✨🌐
  funniture-fe/src/apis/ReviewAPI.js
  funniture-fe/src/pages/common/Inquiry.js
  funniture-fe/src/pages/common/ProductDetailPage.js
  funniture-fe/src/pages/common/Review.js
  funniture-fe/src/pages/common/reviewProduct.module.css
  funniture-fe/src/pages/user/UserInquiry.js
Labels: ✨Feature✨, 📅ToDo📅, 🎨CSS🎨

#313 ✨ [PR] 2025/03/08 1:1문의 완성 - 정예진 ✨
  funniture-fe/src/App.js
  funniture-fe/src/apis/AdminInquiryAPI.js
  funniture-fe/src/assets/icon/arrows-rotate-solid.svg
  funniture-fe/src/component/ChatModal.js
  funniture-fe/src/component/ChatModal.module.css
  funniture-fe/src/component/Header.js
  funniture-fe/src/layouts/AdminLayout.js
  funniture-fe/src/layouts/OwnerLayout.js
  funniture-fe/src/layouts/UserRouter.js
  funniture-fe/src/pages/admin/AdminDirectPage.js
  funniture-fe/src/pages/admin/AdminDirectPage.module.css
  funniture-fe/src/pages/admin/AdminQnAPage.js
  funniture-fe/src/pages/common/NotAllow.js
Labels: 🔨Refactor🔨, ✨Feature✨, 📅ToDo📅, ✅PR✅, 🎨CSS🎨

#315 :sparkles: [PR] 2024/03/09 공지사항 조회, 등록, 삭제 - 정예진 :sparkles:
  funniture-fe/src/App.js
  funniture-fe/src/apis/NoticeAPI.js
  funniture-fe/src/pages/admin/AdminConvert.js
  funniture-fe/src/pages/admin/AdminLeaver.js
  funniture-fe/src/pages/admin/AdminNotice.js
  funniture-fe/src/pages/admin/AdminNotice.module.css
  funniture-fe/src/pages/admin/AdminOwner.js
  funniture-fe/src/pages/admin/AdminUser.js
  funniture-fe/src/pages/admin/rental.module.css
  funniture-fe/src/pages/common/Main.js
  funniture-fe/src/pages/common/inquiryProduct.module.css
  funniture-fe/src/pages/common/main.css
  funniture-fe/src/pages/login/Login.js
  funniture-fe/src/pages/user/UserInquiry.js
  funniture-fe/src/pages/user/mypageInquiry.module.css
  funniture-fe/src/pages/user/mypagereview.module.css
  funniture-fe/src/pages/user/ordersReturn.module.css
  funniture-fe/src/pages/user/rentalRegist.module.css
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅, 🎨CSS🎨

#317 :globe_with_meridians:[PR] 2025/03/09 main에 공지사항 연결 및 권한에 따라 보이는거 제한 …
  funniture-fe/src/App.js
  funniture-fe/src/pages/common/Main.js
  funniture-fe/src/pages/common/Notice.js
  funniture-fe/src/pages/common/main.css
  funniture-fe/src/pages/common/notice.module.css
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅, 🎨CSS🎨

#320 :sparkles: [PR] 2025/03/09 제공자 업체정보 페이지 완성 - 정예진 :sparkles:
  funniture-fe/src/App.js
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/layouts/OwnerLayout.js
  funniture-fe/src/layouts/ownerlayout.css
  funniture-fe/src/pages/common/Main.js
  funniture-fe/src/pages/common/Notice.js
  funniture-fe/src/pages/owner/OwnerInfo.js
  funniture-fe/src/pages/owner/OwnerInfo.module.css
  funniture-fe/src/pages/owner/OwnerMyPage.js
  funniture-fe/src/pages/owner/OwnerNotice.js
  funniture-fe/src/pages/owner/OwnerNoticeDetail.js
  funniture-fe/src/pages/owner/ownerNotice.module.css
  funniture-fe/src/pages/owner/ownermypage.module.css
  funniture-fe/src/redux/modules/OwnerModule.js
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅, 🎨CSS🎨

#321 🌐✨[PR]2025/03/09 제공자 메인 페이지 / 리뷰 페이지 연결 - 김규남✨🌐
  funniture-fe/src/App.js
  funniture-fe/src/apis/InquiryAPI.js
  funniture-fe/src/apis/ReviewAPI.js
  funniture-fe/src/pages/owner/OwnerMyPage.js
  funniture-fe/src/pages/owner/OwnerReview.js
  funniture-fe/src/pages/owner/ownerMainReview.module.css
  funniture-fe/src/pages/owner/ownerReview.module.css
  funniture-fe/src/pages/owner/ownermypage.module.css
  funniture-fe/src/redux/modules/OwnerModule.js
Labels: ✨Feature✨, 📅ToDo📅, 🎨CSS🎨

#323 :globe_with_meridians:[PR]2025/03/09 월별 관리자 매출현황 조회 및 회사별 필터링 - 정은미:globe_with_meridians:
  funniture-fe/src/App.js
  funniture-fe/src/apis/RentalAPI.js
  funniture-fe/src/pages/admin/AdminSales.js
  funniture-fe/src/pages/admin/adminSales.module.css
Labels: ✨Feature✨

#325 💄🌐✨[PR]2025/03/09 사용자 마이페이지 작성한 리뷰 , 작성 가능 리뷰 / 페이지 네이션 - 김규남✨ 🌐💄
  funniture-fe/src/apis/ReviewAPI.js
  funniture-fe/src/pages/user/UserInquiry.js
  funniture-fe/src/pages/user/UserReview.js
  funniture-fe/src/pages/user/mypagereview.module.css
  funniture-fe/src/redux/modules/MemberModule.js
Labels: ✨Feature✨, 📅ToDo📅, 🎨CSS🎨

#327 🌐✨[PR]2025/03/09 메인페이지 리뷰 데이터 출력 - 김규남✨🌐
  funniture-fe/src/apis/InquiryAPI.js
  funniture-fe/src/apis/ReviewAPI.js
  funniture-fe/src/pages/common/Main.js
  funniture-fe/src/pages/common/main.css
  funniture-fe/src/pages/owner/OwnerMyPage.js
  funniture-fe/src/redux/modules/MemberModule.js
  funniture-fe/src/redux/modules/OwnerModule.js
Labels: ✨Feature✨, 📅ToDo📅, 🎨CSS🎨

#330 🌐✨[PR]2025/03/10 사용자 페이지 리뷰 등록 - 김규남 ✨🌐
  funniture-fe/src/apis/InquiryAPI.js
  funniture-fe/src/apis/ReviewAPI.js
  funniture-fe/src/pages/user/UserReview.js
  funniture-fe/src/pages/user/mypagereview.module.css
Labels: ✨Feature✨, 📅ToDo📅, 🎨CSS🎨

#333 :art:[PR]2025/03/10 관리자 예약정보 단일 드롭다운 형식으로 수정 - 정은미:art:
  funniture-fe/src/pages/admin/Rental.js
Labels: 🔨Refactor🔨

#336 :art:[PR]2025/03/10 사용자 마이페이지 프로필사진&반납예정가능건수&배송지 등록 CSS 수정 - 정은미:art:
  funniture-fe/src/assets/images/userDefault.jpg
  funniture-fe/src/layouts/AdminLayout.js
  funniture-fe/src/layouts/OwnerLayout.js
  funniture-fe/src/layouts/UserRouter.js
  funniture-fe/src/pages/owner/OwnerMyPage.js
  funniture-fe/src/pages/user/DeliveryAddress.js
  funniture-fe/src/pages/user/DetailOrder.js
  funniture-fe/src/pages/user/MyPage.js
  funniture-fe/src/pages/user/deliveryAddress.module.css
  funniture-fe/src/pages/user/detailorder.module.css
Labels: 🔨Refactor🔨

#337 🌐✨[PR]2025/03/10 문의 답변 / 유효성 검사 - 김규남 ✨🌐
  funniture-fe/src/apis/InquiryAPI.js
  funniture-fe/src/pages/owner/OwnerInquiry.js
  funniture-fe/src/pages/owner/ownerInquiry.module.css
Labels: ✨Feature✨, 📅ToDo📅, 🎨CSS🎨

#338 :art:[PR]2025/03/10 렌탈 시 할인율 전체 적용 -정은미:art:
  funniture-fe/src/pages/admin/AdminSales.js
  funniture-fe/src/pages/owner/OwnerSales.js
  funniture-fe/src/pages/user/DetailOrder.js
  funniture-fe/src/pages/user/Orders.js
  funniture-fe/src/pages/user/RentalRegist.js
Labels: 🔨Refactor🔨

#341 ✨ [PR] 2025/03/10 접속자 수 반영 및 조회 - 정예진 ✨
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/pages/admin/AdminProduct.js
  funniture-fe/src/pages/admin/adminSales.module.css
  funniture-fe/src/pages/owner/OwnerMyPage.js
  funniture-fe/src/pages/owner/ownerInquiry.module.css
  funniture-fe/src/pages/owner/ownerReview.module.css
  funniture-fe/src/pages/owner/ownermypage.module.css
  funniture-fe/src/pages/user/orders.module.css
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅, 🎨CSS🎨

#342 :art:[PR]2025/03/11 사용자 주문 금액 수정 - 정은미:art:
  funniture-fe/src/pages/user/DetailOrder.js
  funniture-fe/src/pages/user/Orders.js
Labels: 🔨Refactor🔨

#343 :lipstick: [PR] 2025/03/11 제공자 main css 변경 - 정예진 :lipstick:
  funniture-fe/src/pages/owner/OwnerInquiry.js
  funniture-fe/src/pages/owner/OwnerMyPage.js
  funniture-fe/src/pages/owner/ownerInquiry.module.css
  funniture-fe/src/pages/owner/ownerNotice.module.css
  funniture-fe/src/pages/owner/ownermypage.module.css
Labels: 🎨CSS🎨

#345 :sparkles:[PR]2025/03/11 제공자 마이페이지 메인 예약현황 카운트 - 정은미:sparkles:
  funniture-fe/src/apis/RentalAPI.js
  funniture-fe/src/pages/owner/OwnerMyPage.js
Labels: ✨Feature✨

#347 🌐✨[PR]2025/03/11 제공자 문의 답변에 따른 사용자 페이지 연결 - 김규남 ✨🌐
  funniture-fe/src/apis/InquiryAPI.js
  funniture-fe/src/pages/user/UserInquiry.js
  funniture-fe/src/pages/user/mypageInquiry.module.css
Labels: ✨Feature✨, 📅ToDo📅, 🎨CSS🎨

#349 :globe_with_meridians:[PR]2025/03/11 계약만료 갯수 카운트 - 정은미:globe_with_meridians:
  funniture-fe/src/apis/RentalAPI.js
  funniture-fe/src/pages/owner/OwnerMyPage.js
  funniture-fe/src/pages/user/MyPage.js
  funniture-fe/src/pages/user/Orders.js
  funniture-fe/src/pages/user/OrdersReturn.js
Labels: ✨Feature✨

#352 :globe_with_meridians:[PR]2025/03/11 제공자 이번 달 매출 차트 - 정은미:globe_with_meridians:
  funniture-fe/src/apis/RentalAPI.js
  funniture-fe/src/pages/owner/OwnerMyPage.js
  funniture-fe/src/pages/owner/ownermypage.module.css
Labels: ✨Feature✨

#354 🌐✨[PR]2025/03/11 제공자 문의 답변에 따른 상세페이지 연결 - 김규남✨ 🌐
  funniture-fe/src/apis/InquiryAPI.js
  funniture-fe/src/pages/common/Inquiry.js
  funniture-fe/src/pages/common/inquiryProduct.module.css
  funniture-fe/src/pages/owner/OwnerInquiry.js
  funniture-fe/src/pages/owner/OwnerMyPage.js
  funniture-fe/src/pages/owner/ownermypage.module.css
  funniture-fe/src/pages/user/UserInquiry.js
  funniture-fe/src/pages/user/UserReview.js
  funniture-fe/src/redux/modules/MemberModule.js
  funniture-fe/src/redux/modules/OwnerModule.js
Labels: ✨Feature✨, 📅ToDo📅, 🎨CSS🎨

#356 :sparkles: [PR] 2025/03/11 관리자 그래프 작업중 - 정예진 :sparkles:
  funniture-fe/src/pages/admin/AdminMain.js
  funniture-fe/src/pages/admin/adminMain.module.css
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅, 🎨CSS🎨

#358 :sparkles:[PR]2025/03/12 관리자 매출현황 차트(월별,일별) - 정은미:sparkles:
  funniture-fe/src/apis/RentalAPI.js
  funniture-fe/src/pages/admin/AdminMain.js
  funniture-fe/src/pages/user/DetailOrder.js
  funniture-fe/src/pages/user/MyPage.js
  funniture-fe/src/pages/user/Orders.js
  funniture-fe/src/pages/user/detailorder.module.css
  funniture-fe/src/pages/user/orders.module.css
Labels: ✨Feature✨

#359 :globe_with_meridians: [PR]2025/03/12 관리자 메인 이번 달 매출 업체 TOP5 - 정은미:globe_with_meridians:
  funniture-fe/src/apis/RentalAPI.js
  funniture-fe/src/pages/admin/AdminMain.js
Labels: ✨Feature✨

#361 :art:[PR]2025/03/12 사용자 상세페이지 예약취소 수정 - 정은미:art:
  funniture-fe/src/pages/user/DetailOrder.js
  funniture-fe/src/pages/user/detailorder.module.css
  funniture-fe/src/pages/user/orders.module.css
Labels: 🔨Refactor🔨

#362 📝[PR]2025/03/12 문의 삭제 수정 등 - 김규남📝
  funniture-fe/src/pages/user/UserReview.js
Labels: ✅PR✅, 🎨CSS🎨

#363 :bug:[PR]2025/03/12 사용자 배송지관리 삭제&신규배송지 등록(모달)&사용자 마이페이지 진행상태 카운트 수정 - 정은미:bug:
  funniture-fe/src/pages/user/DeliveryAddress.js
  funniture-fe/src/pages/user/DeliveryAddressModal.js
  funniture-fe/src/pages/user/MyPage.js
Labels: 🔨Refactor🔨

#366 :lipstick:[PR]2025/03/12 관리자 테두리 굵기 통합 - 정은미:lipstick:
  funniture-fe/src/pages/admin/adminProduct.module.css
  funniture-fe/src/pages/admin/adminSales.module.css
  funniture-fe/src/pages/admin/rental.module.css
  funniture-fe/src/pages/owner/OwnerSales.js
Labels: 🎨CSS🎨

#367 💄 전체 CSS 점검 - 정예진 💄
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/apis/ProductAPI.js
  funniture-fe/src/component/BtnModal.module.css
  funniture-fe/src/layouts/ownerlayout.css
  funniture-fe/src/pages/admin/AdminMain.js
  funniture-fe/src/pages/admin/adminMain.module.css
  funniture-fe/src/pages/common/ListPage.js
  funniture-fe/src/pages/common/main.css
  funniture-fe/src/pages/login/login.css
  funniture-fe/src/pages/login/signup.css
  funniture-fe/src/pages/owner/OwnerMyPage.js
  funniture-fe/src/pages/owner/OwnerRental.js
  funniture-fe/src/pages/owner/OwnerReview.js
  funniture-fe/src/pages/owner/ownerMainInquiry.module.css
  funniture-fe/src/pages/owner/ownerMainReview.module.css
  funniture-fe/src/pages/owner/ownerRental.module.css
  funniture-fe/src/pages/owner/ownerReview.module.css
  funniture-fe/src/pages/owner/ownermypage.module.css
  funniture-fe/src/pages/user/MyPage.js
  funniture-fe/src/pages/user/UserInquiry.js
  funniture-fe/src/pages/user/UserReview.js
  funniture-fe/src/pages/user/mypageInquiry.module.css
  funniture-fe/src/pages/user/mypagereview.module.css
  funniture-fe/src/pages/user/orders.module.css
Labels: 🎨CSS🎨

#369 💄[PR]2025/03/13 리뷰 작성 입력 안 되던 거 수정 - 김규남 💄
  funniture-fe/src/pages/admin/AdminConvert.js
  funniture-fe/src/pages/user/UserReview.js
Labels: 📅ToDo📅, 🎨CSS🎨

#370 :art:[PR]2025/03/13 확인용 구문 제거 - 정은미:art:
  funniture-fe/src/apis/RentalAPI.js
  funniture-fe/src/pages/admin/AdminMain.js
  funniture-fe/src/pages/user/MyPage.js
  funniture-fe/src/pages/user/Orders.js
  funniture-fe/src/pages/user/OrdersReturn.js
  funniture-fe/src/pages/user/RentalRegist.js
Labels: 🔨Refactor🔨

#371 📝[PR]2025/03/13 console 구문 삭제 , 주석 삭제 -김규남 📝
  funniture-fe/src/App.js
  funniture-fe/src/apis/AdminAPI.js
  funniture-fe/src/apis/Apis.js
  funniture-fe/src/apis/InquiryAPI.js
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/apis/ReviewAPI.js
  funniture-fe/src/pages/admin/AdminConvert.js
  funniture-fe/src/pages/admin/AdminLeaver.js
  funniture-fe/src/pages/admin/AdminOwner.js
  funniture-fe/src/pages/admin/AdminUser.js
  funniture-fe/src/pages/common/Inquiry.js
  funniture-fe/src/pages/login/Login.js
  funniture-fe/src/pages/owner/OwnerInquiry.js
  funniture-fe/src/pages/owner/OwnerMyPage.js
  funniture-fe/src/pages/owner/OwnerReview.js
  funniture-fe/src/pages/user/AppConvert.js
  funniture-fe/src/pages/user/Convert.js
  funniture-fe/src/pages/user/EditsInfo.js
  funniture-fe/src/pages/user/UserConform.js
  funniture-fe/src/pages/user/UserInquiry.js
  funniture-fe/src/pages/user/UserReview.js
Labels: ✅PR✅

#372 📝 [PR] 2025/03/13 console 정리 - 정예진 📝
  funniture-fe/src/App.js
  funniture-fe/src/apis/AdminInquiryAPI.js
  funniture-fe/src/apis/ChatAPI.js
  funniture-fe/src/apis/FavoriteAPI.js
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/apis/NoticeAPI.js
  funniture-fe/src/apis/ProductAPI.js
  funniture-fe/src/apis/ReviewAPI.js
  funniture-fe/src/component/ChatModal.js
  funniture-fe/src/component/Header.js
  funniture-fe/src/layouts/AdminLayout.js
  funniture-fe/src/layouts/LoginRouter.js
  funniture-fe/src/layouts/OwnerLayout.js
  funniture-fe/src/layouts/UserLayout.js
  funniture-fe/src/layouts/UserRouter.js
  funniture-fe/src/pages/admin/AdminConvert.js
  funniture-fe/src/pages/admin/AdminDirectPage.js
  funniture-fe/src/pages/admin/AdminMain.js
  funniture-fe/src/pages/admin/AdminManageChat.js
  funniture-fe/src/pages/admin/AdminNotice.js
  funniture-fe/src/pages/admin/AdminProduct.js
  funniture-fe/src/pages/admin/AdminQnAPage.js
  funniture-fe/src/pages/admin/AdminUser.js
  funniture-fe/src/pages/common/Inquiry.js
  funniture-fe/src/pages/common/ListPage.js
  funniture-fe/src/pages/common/Main.js
  funniture-fe/src/pages/common/Notice.js
  funniture-fe/src/pages/common/ProductDetailPage.js
  funniture-fe/src/pages/common/Review.js
  funniture-fe/src/pages/login/Login.js
  funniture-fe/src/pages/owner/OwnerInquiry.js
  funniture-fe/src/pages/owner/OwnerMyPage.js
  funniture-fe/src/pages/owner/OwnerNotice.js
  funniture-fe/src/pages/owner/OwnerNoticeDetail.js
  funniture-fe/src/pages/owner/OwnerProducts.js
  funniture-fe/src/pages/owner/OwnerRegister.js
  funniture-fe/src/pages/owner/OwnerReview.js
  funniture-fe/src/pages/user/AppConvert.js
  funniture-fe/src/pages/user/FavoritesPage.js
  funniture-fe/src/pages/user/Recentproduct.js
  funniture-fe/src/pages/user/RentalRegist.js
  funniture-fe/src/pages/user/UserInquiry.js
Labels: 🚫Error🚫, 🔨Refactor🔨, 📅ToDo📅, ✅PR✅

#373 제공자 정산 회원명 수정
  funniture-fe/src/pages/owner/OwnerSales.js
Labels: 🔨Refactor🔨

#381 :art:[PR]2025/03/14 예약등록 상품이미지 연결&수거중 확인모달창 수정 - 정은미:art:
  funniture-fe/src/pages/common/ProductDetailPage.js
  funniture-fe/src/pages/owner/OwnerRental.js
  funniture-fe/src/pages/user/Orders.js
  funniture-fe/src/pages/user/RentalRegist.js
Labels: 🔨Refactor🔨

#383 📝 [PR]2025/03/14 index.html react quill 주석 해체 - 김규남 📝
  funniture-fe/public/index.html
Labels: 🔨Refactor🔨
