Repository funniture-Project/funniture-fe, pull requests merged in 2025-02, with the labels that each got.

#5 :lipstick: 전체 페이지 레이아웃 잡기 :lipstick:
  funniture-fe/public/index.html
  funniture-fe/src/App.js
  funniture-fe/src/assets/icon/search-icon.svg
  funniture-fe/src/assets/images/banner(1).png
  funniture-fe/src/assets/images/logo-image-white.png
  funniture-fe/src/assets/images/mainLogo.png
  funniture-fe/src/assets/images/profiletest.jpg
  funniture-fe/src/assets/images/text_logo-white.png
  funniture-fe/src/component/Footer.js
  funniture-fe/src/component/Header.js
  funniture-fe/src/component/headerfooter.css
  funniture-fe/src/index.js
  funniture-fe/src/layouts/AdminLayout.js
  funniture-fe/src/layouts/CommonLayout.js
  funniture-fe/src/layouts/OwnerLayout.js
  funniture-fe/src/layouts/UserLayout.js
  funniture-fe/src/layouts/adminlayout.css
  funniture-fe/src/layouts/ownerlayout.css
  funniture-fe/src/layouts/userLayout.css
  funniture-fe/src/modules/ProductModules.js
  funniture-fe/src/pages/Main.js
  funniture-fe/src/pages/Test.js
  funniture-fe/src/pages/main.css
  funniture-fe/src/pages/owner/OwnerMyPage.js
  funniture-fe/src/pages/owner/ownermypage.css
  funniture-fe/src/pages/user/MyPage.js
  funniture-fe/src/pages/user/mypage.css
  funniture-fe/src/store.js
Labels: 📅ToDo📅, ✅PR✅, 🎨CSS🎨

#6 Dev
  funniture-fe/public/index.html
  funniture-fe/src/App.js
  funniture-fe/src/assets/icon/search-icon.svg
  funniture-fe/src/assets/images/banner(1).png
  funniture-fe/src/assets/images/logo-image-white.png
  funniture-fe/src/assets/images/mainLogo.png
  funniture-fe/src/assets/images/profiletest.jpg
  funniture-fe/src/assets/images/text_logo-white.png
  funniture-fe/src/component/Footer.js
  funniture-fe/src/component/Header.js
  funniture-fe/src/component/headerfooter.css
  funniture-fe/src/index.js
  funniture-fe/src/layouts/AdminLayout.js
  funniture-fe/src/layouts/CommonLayout.js
  funniture-fe/src/layouts/OwnerLayout.js
  funniture-fe/src/layouts/UserLayout.js
  funniture-fe/src/layouts/adminlayout.css
  funniture-fe/src/layouts/ownerlayout.css
  funniture-fe/src/layouts/userLayout.css
  funniture-fe/src/modules/ProductModules.js
  funniture-fe/src/pages/Main.js
  funniture-fe/src/pages/Test.js
  funniture-fe/src/pages/main.css
  funniture-fe/src/pages/owner/OwnerMyPage.js
  funniture-fe/src/pages/owner/ownermypage.css
  funniture-fe/src/pages/user/MyPage.js
  funniture-fe/src/pages/user/mypage.css
  funniture-fe/src/store.js
Labels: ✅PR✅, 🎨CSS🎨

#8 :globe_with_meridians: 파일구조 변경 및 프론트 백 연결 :truck:
  funniture-fe/package-lock.json
  funniture-fe/package.json
  funniture-fe/public/Paperlogy-1Thin.ttf
  funniture-fe/public/Paperlogy-2ExtraLight.ttf
  funniture-fe/public/Paperlogy-3Light.ttf
  funniture-fe/public/Paperlogy-4Regular.ttf
  funniture-fe/public/Paperlogy-5Medium.ttf
  funniture-fe/public/Paperlogy-6SemiBold.ttf
  funniture-fe/public/Paperlogy-7Bold.ttf
  funniture-fe/public/Paperlogy-8ExtraBold.ttf
  funniture-fe/public/Paperlogy-9Black.ttf
  funniture-fe/src/apis/ProductAPI.js
  funniture-fe/src/assets/images/air_purifier.png
  funniture-fe/src/assets/images/banner(2).jpg
  funniture-fe/src/assets/images/banner(3).jpg
  funniture-fe/src/assets/images/bed.png
  funniture-fe/src/assets/images/dining_table.png
  funniture-fe/src/assets/images/dishwasher.png
  funniture-fe/src/assets/images/dryer.png
  funniture-fe/src/assets/images/kimchi_refrigerator.png
  funniture-fe/src/assets/images/refrigerator.png
  funniture-fe/src/assets/images/sofa.png
  funniture-fe/src/assets/images/washing_machine.png
  funniture-fe/src/assets/images/water_purifier.png
  funniture-fe/src/component/Header.js
  funniture-fe/src/component/headerfooter.css
  funniture-fe/src/font.css
  funniture-fe/src/index.js
  funniture-fe/src/layouts/AdminLayout.js
  funniture-fe/src/layouts/OwnerLayout.js
  funniture-fe/src/layouts/UserLayout.js
  funniture-fe/src/layouts/userLayout.css
  funniture-fe/src/modules/ProductModules.js
  funniture-fe/src/redux/modules/CategoryModuls.js
  funniture-fe/src/redux/modules/index.js
  funniture-fe/src/redux/modules/productReducer.js
  funniture-fe/src/setupProxy.js
  funniture-fe/src/store.js
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅, 🎨CSS🎨

#11 💄 [PR] 2025/2/12 메인페이지 구조 잡기 완료-정예진 💄
  funniture-fe/src/assets/icon/communication.svg
  funniture-fe/src/assets/icon/notice_icon.svg
  funniture-fe/src/assets/icon/review.svg
  funniture-fe/src/layouts/userLayout.css
  funniture-fe/src/pages/Main.js
  funniture-fe/src/pages/main.css
  funniture-fe/src/pages/user/MyPage.js
  funniture-fe/src/redux/modules/CategoryModuls.js
Labels: 📅ToDo📅, 🎨CSS🎨

#12 :twisted_rightwards_arrows:[PR]20250213 dev에서 main으로 marge-정은미:twisted_rightwards_arrows:
  funniture-fe/src/assets/icon/communication.svg
  funniture-fe/src/assets/icon/notice_icon.svg
  funniture-fe/src/assets/icon/review.svg
  funniture-fe/src/layouts/userLayout.css
  funniture-fe/src/pages/Main.js
  funniture-fe/src/pages/main.css
  funniture-fe/src/pages/user/MyPage.js
  funniture-fe/src/redux/modules/CategoryModuls.js
Labels: ✅PR✅

#17 🎨[PR] 2025/2/13 검색 페이지 구조 잡기 + 데이터 받아오기 [정예진] 🎨
  funniture-fe/src/App.js
  funniture-fe/src/apis/ProductAPI.js
  funniture-fe/src/component/Header.js
  funniture-fe/src/component/adminpage/AdminTop.js
  funniture-fe/src/component/adminpage/admintop.css
  funniture-fe/src/layouts/AdminLayout.js
  funniture-fe/src/layouts/AuthorityLayout.js
  funniture-fe/src/layouts/UserLayout.js
  funniture-fe/src/layouts/adminlayout.css
  funniture-fe/src/layouts/userLayout.css
  funniture-fe/src/pages/admin/AdminMain.js
  funniture-fe/src/pages/admin/AdminUser.js
  funniture-fe/src/pages/admin/Rental.js
  funniture-fe/src/pages/admin/rental.css
  funniture-fe/src/pages/common/ListPage.js
  funniture-fe/src/pages/common/Main.js
  funniture-fe/src/pages/common/listpage.css
  funniture-fe/src/pages/common/main.css
Labels: 📅ToDo📅, ✅PR✅, 🎨CSS🎨

#21 💄 [PR]2025/02/13 로그인 및 회원 가입 페이지 CSS 적용 -김규남💄
  funniture-fe/src/App.js
  funniture-fe/src/component/Header.js
  funniture-fe/src/pages/login/Login.js
  funniture-fe/src/pages/login/Singup.js
  funniture-fe/src/pages/login/login.css
  funniture-fe/src/pages/login/signup.css
Labels: 🎨CSS🎨

#22 :lipstick:[PR]2025/02/13 관리자 예약정보 프론트엔드 레이아웃잡기-정은미:lipstick:
  funniture-fe/src/layouts/adminlayout.css
  funniture-fe/src/pages/admin/Rental.js
  funniture-fe/src/pages/admin/rental.css
Labels: 🎨CSS🎨

#28 [PR] 2025/2/14 refcategory 별 검색 되도록 수정-정예진🎨
  funniture-fe/src/apis/ProductAPI.js
  funniture-fe/src/layouts/UserLayout.js
  funniture-fe/src/pages/common/ListPage.js
  funniture-fe/src/redux/modules/CategoryModuls.js
Labels: 🔨Refactor🔨, 📅ToDo📅

#29 :lipstick:[PR]2025/02/14 관리자 예약정보 프론트엔드 레이아웃 수정-정은미:lipstick:
  funniture-fe/src/assets/icon/angle-left-solid.svg
  funniture-fe/src/assets/icon/angle-right-solid.svg
  funniture-fe/src/assets/icon/angles-left-solid.svg
  funniture-fe/src/assets/icon/angles-right-solid.svg
  funniture-fe/src/pages/admin/Rental.js
  funniture-fe/src/pages/admin/rental.css
  funniture-fe/src/pages/admin/rental.module.css
Labels: 🔨Refactor🔨, 🎨CSS🎨

#30 :sparkles: [PR] 2025/2/14 카테고리별 제공자 리스트 조회-정예진 :sparkles:
  funniture-fe/package-lock.json
  funniture-fe/package.json
  funniture-fe/src/apis/ProductAPI.js
  funniture-fe/src/component/Footer.js
  funniture-fe/src/component/Header.js
  funniture-fe/src/component/headerfooter.module.css
  funniture-fe/src/layouts/UserLayout.js
  funniture-fe/src/pages/common/ListPage.js
  funniture-fe/src/setupProxy.js
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅

#31 :globe_with_meridians:[PR]2025/02/14 관리자 예약조회 프론트&백 연결-정은미:globe_with…
  funniture-fe/src/apis/RentalAPI.js
  funniture-fe/src/pages/admin/Rental.js
Labels: ✨Feature✨

#35 :art: [PR] 2025/2/15 제공자 검색 조건 연결 및 제공자 선택 수정-정예진 :art:
  funniture-fe/src/App.js
  funniture-fe/src/apis/ProductAPI.js
  funniture-fe/src/component/Header.js
  funniture-fe/src/layouts/UserLayout.js
  funniture-fe/src/layouts/userLayout.css
  funniture-fe/src/pages/common/ListPage.js
  funniture-fe/src/redux/modules/CategoryModuls.js
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅, 🎨CSS🎨

#37 :globe_with_meridians:[PR]2025/02/16 관리자 검색조건으로 예약조회 프론트&백 연결-정은미:globe_with_meridians:
  funniture-fe/src/apis/RentalAPI.js
  funniture-fe/src/pages/admin/Rental.js
  funniture-fe/src/pages/admin/rental.module.css
Labels: ✨Feature✨

#38 ✨ [PR] 2025/2/16 top down 버튼 생성-정예진✨
  funniture-fe/src/assets/icon/circle-down.svg
  funniture-fe/src/assets/icon/circle-up.svg
  funniture-fe/src/assets/icon/down-arrow.svg
  funniture-fe/src/assets/icon/up-arrow.svg
  funniture-fe/src/component/TopDownBtn.js
  funniture-fe/src/component/headerfooter.module.css
  funniture-fe/src/component/topdownbtn.module.css
  funniture-fe/src/index.js
  funniture-fe/src/layouts/UserLayout.js
  funniture-fe/src/utils/ScrollToTop.js
Labels: ✨Feature✨, 📅ToDo📅, 🎨CSS🎨

#41 :art:[PR]2025/02/17 관리자 예약정보 검색 필터링 수정 -정은미:art:
  funniture-fe/src/apis/RentalAPI.js
  funniture-fe/src/assets/icon/rotate-right-solid.svg
  funniture-fe/src/pages/admin/Rental.js
  funniture-fe/src/pages/admin/rental.module.css
Labels: 🔨Refactor🔨

#44 :sparkles: [PR]2025/02/17 관리자 예약정보 검색조건 초기화-정은미:sparkles:
  funniture-fe/src/pages/admin/Rental.js
  funniture-fe/src/pages/admin/rental.module.css
Labels: ✨Feature✨

#46 :art:[PR]2025/02/17 관리자 예약정보 예외처리-정은미:art:
  funniture-fe/src/pages/admin/Rental.js
  funniture-fe/src/pages/admin/rental.module.css
Labels: ✨Feature✨

#47 ✨[PR]2025/02/17 회원가입 (프론트 / 백 연결) - 김규남✨
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/pages/login/Singup.js
  funniture-fe/src/redux/modules/MemberModule.js
Labels: ✨Feature✨

#49 ✨ [PR] 2025/2/17 관리자 제품 관리 완성-정예진 ✨
  funniture-fe/src/apis/ProductAPI.js
  funniture-fe/src/component/Pagination.js
  funniture-fe/src/component/pagination.module.css
  funniture-fe/src/pages/admin/AdminProduct.js
  funniture-fe/src/pages/admin/Rental.js
  funniture-fe/src/pages/admin/adminProduct.module.css
  funniture-fe/src/pages/admin/rental.module.css
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅, 🎨CSS🎨

#50 ✨[PR]2025/02/17 프론트-백엔드 로그인 연결 - 김규남✨
  funniture-fe/src/apis/.env
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/pages/login/Login.js
  funniture-fe/src/pages/login/Singup.js
  funniture-fe/src/redux/modules/MemberModule.js
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅

#51 ✨[PR]2025/02/17 중복 회원가입 검증 / 로그인 검증 - 김규남✨
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/pages/login/Login.js
Labels: ✨Feature✨, ✅PR✅

#53 ✨[PR]2025/02/18 서버에서 받아온 토큰에서 id 꺼내기 - 김규남 ✨
  funniture-fe/package-lock.json
  funniture-fe/package.json
  funniture-fe/src/App.js
  funniture-fe/src/component/Header.js
  funniture-fe/src/pages/login/Login.js
  funniture-fe/src/pages/user/Inquiry.js
  funniture-fe/src/utils/tokenUtils.js
Labels: 📅ToDo📅

#56 :sparkles: [PR] 2025/2/18 상품 상태 정보 변경 완료 [정예진] :sparkles:
  funniture-fe/src/apis/ProductAPI.js
  funniture-fe/src/pages/admin/AdminMain.js
  funniture-fe/src/pages/admin/AdminProduct.js
  funniture-fe/src/pages/common/ListPage.js
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅

#57 🌐✨[PR]2025/02/18 로그인 한 유저의 대한 정보 가져오기 - 김규남✨🌐
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/pages/login/Login.js
  funniture-fe/src/redux/modules/MemberModule.js
Labels: ✨Feature✨, ✅PR✅

#59 💄 [PR] 2025/2/18 제공자 등록상품 css 페이지 완성 [정예진] 💄
  funniture-fe/src/apis/ProductAPI.js
  funniture-fe/src/component/Header.js
  funniture-fe/src/component/headerfooter.module.css
  funniture-fe/src/pages/common/ListPage.js
  funniture-fe/src/pages/common/Main.js
  funniture-fe/src/pages/login/Login.js
  funniture-fe/src/pages/owner/OwnerProducts.js
  funniture-fe/src/pages/owner/ownerProduct.module.css
Labels: 📅ToDo📅, 🎨CSS🎨

#60 ✨⚡️[PR]2025/02/18 서버에서 프론트로 데이터 불러오기 / 코드 수정-김규남⚡️✨
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/pages/login/Login.js
  funniture-fe/src/redux/modules/MemberModule.js
  funniture-fe/src/redux/modules/index.js
  funniture-fe/src/utils/tokenUtils.js
Labels: 🚫Error🚫, ✨Feature✨, ✅PR✅

#68 🎨🚚 로그인한 회원 정보 받아오고, 새로고침 시 데이터가 초기값으로 변경되는 현상 - 김규남 🎨🚚
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/component/Header.js
  funniture-fe/src/pages/common/Main.js
  funniture-fe/src/redux/modules/MemberModule.js
Labels: 🚫Error🚫, 🤚Help🤚

#70 :lipstick:[PR]2025/02/19 사용자의 마이페이지 진행도&탭 css-정은미:lipstick:
  funniture-fe/src/App.js
  funniture-fe/src/assets/icon/check-solid.svg
  funniture-fe/src/assets/icon/clock-rotate-left-solid.svg
  funniture-fe/src/assets/icon/sack-dollar-solid.svg
  funniture-fe/src/assets/icon/truck-solid.svg
  funniture-fe/src/pages/user/MyPage.js
  funniture-fe/src/pages/user/Orders.js
  funniture-fe/src/pages/user/mypage.css
Labels: 🎨CSS🎨

#71 🎨⚡️[PR]2025/02/19 로그인 시 최상위 컴포넌트에 정보 저장 - 김규남 🎨⚡️
  funniture-fe/src/App.js
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/component/Header.js
  funniture-fe/src/pages/login/Login.js
Labels: 🔨Refactor🔨, ✨Feature✨, 📅ToDo📅

#72 ✨ [PR]2025/02/19 마이페이지 이미지 svg 설정 / 권한에 따른 마이페이지 이동 - 김규남 ✨
  funniture-fe/src/assets/images/circle-user.svg
  funniture-fe/src/component/Header.js
  funniture-fe/src/component/headerfooter.module.css
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅, 🎨CSS🎨

#73 💄[PR] 2025/02/19 제공자 상품 관리 페이지 상태 수정 연결 완료 [정예진] 🌐
  funniture-fe/src/apis/ProductAPI.js
  funniture-fe/src/pages/admin/AdminProduct.js
  funniture-fe/src/pages/common/Main.js
  funniture-fe/src/pages/owner/OwnerProducts.js
  funniture-fe/src/pages/owner/ownerProduct.module.css
  funniture-fe/src/redux/modules/MemberModule.js
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅, 🎨CSS🎨

#74 :lipstick:[PR]2025/02/19 사용자 마이페이지 주문/배송 CSS-정은미:lipstick:
  funniture-fe/src/assets/images/testImg.JPG
  funniture-fe/src/pages/user/Orders.js
  funniture-fe/src/pages/user/mypage.css
  funniture-fe/src/pages/user/orders.module.css
Labels: 🎨CSS🎨

#75 :lipstick: [PR] 2025/02/19 제공자 상품 등록 페이지 뼈대잡기 - 정예진 :lipstick:
  funniture-fe/src/App.js
  funniture-fe/src/apis/RentalAPI.js
  funniture-fe/src/pages/owner/OwnerProducts.js
  funniture-fe/src/pages/owner/OwnerRegister.js
  funniture-fe/src/pages/owner/ownerRegister.module.css
Labels: 📅ToDo📅, 🎨CSS🎨

#76 :globe_with_meridians:[PR]2025/02/19 사용자 주문조회&개월수 필터링(백&프론트 연결) - 정은미:globe_with_meridians:
  funniture-fe/src/apis/RentalAPI.js
  funniture-fe/src/pages/user/Orders.js
  funniture-fe/src/pages/user/orders.module.css
Labels: ✨Feature✨

#78 ⚡️🚚[PR]2025/02/17 로그인 한 회원 정보 불러오기 axios로 수정 - 김규남🚚⚡️
  funniture-fe/.env
  funniture-fe/package.json
  funniture-fe/src/apis/.env
  funniture-fe/src/apis/Apis.js
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/pages/login/Singup.js
Labels: 🔨Refactor🔨, ✨Feature✨, ✅PR✅

#86 :art: [PR] 2025/02/20 axios 이용한 공용 api로 productAPI 수정 - 정예진 :art:
  funniture-fe/package-lock.json
  funniture-fe/src/App.js
  funniture-fe/src/apis/Apis.js
  funniture-fe/src/apis/ProductAPI.js
  funniture-fe/src/component/Header.js
  funniture-fe/src/pages/admin/AdminProduct.js
  funniture-fe/src/pages/common/ListPage.js
  funniture-fe/src/pages/common/ProductDetailPage.js
  funniture-fe/src/redux/modules/CategoryModuls.js
Labels: 🔨Refactor🔨, 📅ToDo📅, ✅PR✅

#89 :art:[PR]2025/02/20 사용자 마이페이지 탭 버튼 Link 연결 후 눌린 탭 css-정은미:lipstick:
  funniture-fe/src/App.js
  funniture-fe/src/pages/user/DetailOrder.js
  funniture-fe/src/pages/user/MyPage.js
  funniture-fe/src/pages/user/Orders.js
  funniture-fe/src/pages/user/OrdersReturn.js
  funniture-fe/src/pages/user/mypage.css
  funniture-fe/src/pages/user/orders.module.css
Labels: 🔨Refactor🔨, 🎨CSS🎨

#91 :art: [PR] 2025/02/20 productDetail 조회 정보 추가 - 정예진 :art:
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/apis/ProductAPI.js
  funniture-fe/src/pages/common/ProductDetailPage.js
  funniture-fe/src/pages/common/productDetail.module.css
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅, 🎨CSS🎨

#93 ✨💄 [PR]2025/02/20 회원가입 / 로그인 검증 및 css 추가 - 김규남 💄✨
  funniture-fe/src/apis/Apis.js
  funniture-fe/src/pages/login/Login.js
  funniture-fe/src/pages/login/Singup.js
  funniture-fe/src/pages/login/login.css
  funniture-fe/src/pages/login/signup.css
  funniture-fe/src/redux/modules/MemberModule.js
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅, 🎨CSS🎨

#94 :globe_with_meridians:[PR]2025/02/20 예약 상세페이지-백&프론트 연결-정은미:globe_with_meridians:
  funniture-fe/src/apis/RentalAPI.js
  funniture-fe/src/pages/user/DetailOrder.js
Labels: ✨Feature✨

#95 🚑 [PR]2025/02/21 작업을 위해, 로그인 유효성 검증 주석하고 머지 -김규남🚑
  funniture-fe/src/pages/login/Login.js
Labels: 🔨Refactor🔨

#102 :lipstick:[PR]2025/02/21 예약 상세페이지 CSS 수정-정은미:lipstick:
  funniture-fe/src/pages/user/DetailOrder.js
  funniture-fe/src/pages/user/detailorder.module.css
  funniture-fe/src/pages/user/mypage.css
Labels: 🔨Refactor🔨, 🎨CSS🎨

#105 ✨[PR]2025/02/21 로그인 한 회원만 마이페이지 버튼 보이게 설정 - 김규남✨
  funniture-fe/src/component/Header.js
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅

#106 ✨[PR]2025/02/21 로그인 페이지에서 비밀번호 변경 로직 완료 - 김규남✨
  funniture-fe/src/App.js
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/pages/login/FindPass.js
  funniture-fe/src/pages/login/Login.js
  funniture-fe/src/pages/login/login.css
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅

#107 :lipstick:[PR]2025/02/21 예약 등록 페이지 CSS-정은미:lipstick:
  funniture-fe/src/App.js
  funniture-fe/src/pages/user/RentalRegist.js
  funniture-fe/src/pages/user/detailorder.module.css
  funniture-fe/src/pages/user/rentalRegist.module.css
Labels: 🎨CSS🎨

#108 ✨ [PR] 2025/02/21 상품 등록 + 이미지 cloudinary업로드 - 정예진 ✨
  funniture-fe/src/apis/ProductAPI.js
  funniture-fe/src/component/Header.js
  funniture-fe/src/pages/common/ListPage.js
  funniture-fe/src/pages/common/ProductDetailPage.js
  funniture-fe/src/pages/common/productDetail.module.css
  funniture-fe/src/pages/owner/OwnerProducts.js
  funniture-fe/src/pages/owner/OwnerRegister.js
  funniture-fe/src/pages/owner/ownerRegister.module.css
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅, 🎨CSS🎨

#109 :art:[PR]2025/02/21 상품상세페이지 데이터 예약 등록페이지로 연결 - 정은미:art:
  funniture-fe/src/pages/common/ProductDetailPage.js
  funniture-fe/src/pages/user/RentalRegist.js
Labels: ✨Feature✨

#110 ✨[PR]2025/02/21 마이페이지 개인 정보 변경 구현중 - 김규남 ✨
  funniture-fe/src/App.js
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/pages/user/EditsInfo.js
  funniture-fe/src/pages/user/MyPage.js
  funniture-fe/src/pages/user/UserConform.js
  funniture-fe/src/pages/user/editInfo.css
  funniture-fe/src/redux/modules/MemberModule.js
Labels: 📅ToDo📅, ✅PR✅

#115 ✨ [PR] 2025/02/22 공용 모달 작업 완료 - 정예진 ✨
  funniture-fe/package-lock.json
  funniture-fe/package.json
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/component/BtnModal.js
  funniture-fe/src/component/BtnModal.module.css
  funniture-fe/src/component/Header.js
  funniture-fe/src/component/TestContent.js
  funniture-fe/src/component/TopDownBtn.js
  funniture-fe/src/component/testContent.module.css
  funniture-fe/src/layouts/adminlayout.css
  funniture-fe/src/layouts/ownerlayout.css
  funniture-fe/src/pages/admin/adminProduct.module.css
  funniture-fe/src/pages/user/Orders.js
  funniture-fe/src/pages/user/mypage.css
  funniture-fe/src/pages/user/orders.module.css
  funniture-fe/src/redux/modules/MemberModule.js
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅, 🎨CSS🎨

#119 ✨[PR]2025/02/23 사용자 마이페이지 비밀번호 인증 - 김규남 ✨
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/pages/user/UserConform.js
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅

#124 ✨⚡️[PR]2025/02/23 로그인 실패 / 성공 시 모달창 적용 - 김규남 ⚡️✨
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/component/BtnModal.js
  funniture-fe/src/pages/login/Login.js
Labels: 🔨Refactor🔨, ✨Feature✨, 📅ToDo📅, ✅PR✅

#125 ✨[PR]2025/02/23 사용자 마이 페이지 정보 변경 및 불러오기 - 김규남✨
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/pages/login/Login.js
  funniture-fe/src/pages/user/EditsInfo.js
  funniture-fe/src/pages/user/UserConform.js
  funniture-fe/src/pages/user/editsInfo.css
  funniture-fe/src/pages/user/userInfo.css
  funniture-fe/src/redux/modules/MemberModule.js
Labels: 🔨Refactor🔨, ✨Feature✨, 📅ToDo📅, ✅PR✅, 🤚Help🤚

#131 ✨[PR]2025/02/24 사용자 마이 페이지에서 주소 불러오기 - 김규남 ✨
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/pages/user/EditsInfo.js
  funniture-fe/src/redux/modules/MemberModule.js
Labels: 📅ToDo📅, ✅PR✅

#132 ✨[PR]2025/02/24 사용자 마이페이지에서 주소 변경 완료 - 김규남 ✨
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/pages/user/EditsInfo.js
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅

#134 ✨ [PR] 2025/02/24 상품 등록 예외처리 및 완성 - 정예진✨
  funniture-fe/src/apis/ProductAPI.js
  funniture-fe/src/component/BtnModal.js
  funniture-fe/src/component/BtnModal.module.css
  funniture-fe/src/component/headerfooter.module.css
  funniture-fe/src/pages/common/ProductDetailPage.js
  funniture-fe/src/pages/common/productDetail.module.css
  funniture-fe/src/pages/login/Login.js
  funniture-fe/src/pages/owner/OwnerRegister.js
  funniture-fe/src/pages/owner/ownerProduct.module.css
  funniture-fe/src/pages/user/EditsInfo.js
  funniture-fe/src/redux/modules/index.js
  funniture-fe/src/redux/modules/productReducer.js
Labels: ✨Feature✨, 📅ToDo📅, 🎨CSS🎨

#137 ✨[PR]2025/02/24 이미지 파일 업로드 css / 기본 이미지 / 이미지 변경 - 김규남✨
  funniture-fe/src/apis/Apis.js
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/assets/images/Adobe Express - file.png
  funniture-fe/src/component/Header.js
  funniture-fe/src/pages/login/Singup.js
  funniture-fe/src/pages/user/EditsInfo.js
  funniture-fe/src/pages/user/editsInfo.css
Labels: 🔨Refactor🔨, ✨Feature✨, 📅ToDo📅

#139 ✨[PR]2025/02/24 사용자 마이페이지 모든 기능 구현 - 규남 ✨
  funniture-fe/src/App.js
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/component/Header.js
  funniture-fe/src/pages/user/EditsInfo.js
  funniture-fe/src/pages/user/editsInfo.css
  funniture-fe/src/redux/modules/MemberModule.js
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅, 🎨CSS🎨

#141 ✨ [PR] 2025/02/25 상품 등록 및 수정 전면 수정 완료 - 정예진 ✨
  funniture-fe/src/App.js
  funniture-fe/src/apis/ProductAPI.js
  funniture-fe/src/pages/owner/OwnerProducts.js
  funniture-fe/src/pages/owner/OwnerRegister.js
  funniture-fe/src/pages/owner/ownerProduct.module.css
  funniture-fe/src/pages/owner/ownerRegister.module.css
  funniture-fe/src/redux/modules/productReducer.js
Labels: 🔨Refactor🔨, ✨Feature✨, 📅ToDo📅, ✅PR✅

#145 :sparkles:[PR]2025/02/25 배송지 전체 조회 - 백&프론트 연결-정은미:sparkles:
  funniture-fe/src/apis/DeliveryAddressAPI.js
  funniture-fe/src/pages/user/DeliveryAddressModal.js
  funniture-fe/src/pages/user/RentalRegist.js
  funniture-fe/src/pages/user/deliveryAddressModal.module.css
Labels: ✨Feature✨

#150 🎨 [PR] 2025/02/25 상품 등록 및 수정 fe 수정 완료 - 정예진 🎨
  funniture-fe/package-lock.json
  funniture-fe/package.json
  funniture-fe/public/index.html
  funniture-fe/src/apis/ProductAPI.js
  funniture-fe/src/pages/common/productDetail.module.css
  funniture-fe/src/pages/owner/OwnerProducts.js
  funniture-fe/src/pages/owner/OwnerRegister.js
  funniture-fe/src/pages/owner/ownerProduct.module.css
  funniture-fe/src/pages/owner/ownerRegister.module.css
  funniture-fe/src/redux/modules/productReducer.js
Labels: 🔨Refactor🔨, ✨Feature✨, 📅ToDo📅, 🎨CSS🎨

#151 ✨[PR]2025/02/25 로그인 유효성 검증 (아이디 / 비밀번호) - 김규남✨
  funniture-fe/src/pages/login/Login.js
  funniture-fe/src/pages/login/login.css
Labels: ✨Feature✨, 📅ToDo📅, 🎨CSS🎨

#152 :lipstick: [PR] 2025/02/25 제공자 메인에 상품 현황 출력하기 - 정예진 :lipstick:
  funniture-fe/src/pages/owner/OwnerMyPage.js
  funniture-fe/src/pages/owner/ownermypage.module.css
Labels: 📅ToDo📅, 🎨CSS🎨

#154 ✨[PR]2025/02/25 로그인 페이지 비밀번호 찾기 유효성 검증 추가 - 김규남 ✨
  funniture-fe/src/pages/login/FindPass.js
  funniture-fe/src/pages/login/findPass.css
  funniture-fe/src/pages/login/signup.css
  funniture-fe/src/pages/owner/OwnerRegister.js
Labels: ✨Feature✨, 📅ToDo📅, 🎨CSS🎨

#155 :sparkles:[PR]2025/02/25 배송지 선택&완료 모달창-정은미:sparkles:
  funniture-fe/src/pages/user/DeliveryAddressModal.js
  funniture-fe/src/pages/user/RentalRegist.js
  funniture-fe/src/pages/user/deliveryAddressModal.module.css
Labels: ✨Feature✨

#157 ✨ [PR] 2025/02/25 최근 본 상품 api에 넘길 준비 끝 - 정예진 ✨
  funniture-fe/src/App.js
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/pages/common/ProductDetailPage.js
  funniture-fe/src/pages/owner/OwnerMyPage.js
  funniture-fe/src/pages/user/FavoritesPage.js
  funniture-fe/src/pages/user/MyPage.js
  funniture-fe/src/pages/user/RecentProduct.module.css
  funniture-fe/src/pages/user/Recentproduct.js
  funniture-fe/src/pages/user/favoritesPage.module.css
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅, 🎨CSS🎨

#160 :globe_with_meridians:[PR]2025/02/25 예약 등록 백&프론트 연결 -정은미:globe_with_meridians:
  funniture-fe/src/apis/RentalAPI.js
  funniture-fe/src/pages/user/RentalRegist.js
Labels: ✨Feature✨

#162 💄[PR]2025/02/25 사용자의 제공자 전환 요청 페이지 구성 -김규남 💄
  funniture-fe/src/App.js
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/pages/user/AppConvert.js
  funniture-fe/src/pages/user/Convert.js
  funniture-fe/src/pages/user/MyPage.js
  funniture-fe/src/pages/user/appConvert.css
Labels: 📅ToDo📅, 🎨CSS🎨

#168 🌐 [PR]2025/02/26 관리자 페이지 생성 / 서버에서 필요한 데이터 불러옴 - 김규남 🌐
  funniture-fe/src/apis/AdminAPI.js
  funniture-fe/src/layouts/AuthorityLayout.js
  funniture-fe/src/pages/admin/AdminUser.js
  funniture-fe/src/pages/user/AppConvert.js
Labels: 📅ToDo📅

#171 :sparkles: [PR] 2025/02/26 최근 본 상품 완료 - 정예진 :sparkles:
  funniture-fe/src/App.js
  funniture-fe/src/apis/ProductAPI.js
  funniture-fe/src/pages/common/ProductDetailPage.js
  funniture-fe/src/pages/user/RecentProduct.module.css
  funniture-fe/src/pages/user/Recentproduct.js
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅, 🎨CSS🎨

#175 :lipstick:[PR]2025/02/26 예약 완료 시 react-canvas-confetti -정은미:lipstick:
  funniture-fe/package-lock.json
  funniture-fe/package.json
  funniture-fe/src/pages/user/RentalRegist.js
Labels: 🎨CSS🎨

#177 ✨ [PR] 2025/02/26 관심상품 조회 완성 - 정예진 ✨
  funniture-fe/src/apis/FavoriteAPI.js
  funniture-fe/src/pages/common/ListPage.js
  funniture-fe/src/pages/common/ProductDetailPage.js
  funniture-fe/src/pages/user/FavoritesPage.js
  funniture-fe/src/pages/user/favoritesPage.module.css
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅, 🎨CSS🎨

#178 :lipstick:[PR]2025/02/26 제공자별 예약조회 CSS:lipstick:
  funniture-fe/src/App.js
  funniture-fe/src/layouts/OwnerLayout.js
  funniture-fe/src/pages/owner/OwnerRental.js
  funniture-fe/src/pages/owner/ownerRental.module.css
Labels: 🎨CSS🎨

#179 ✨[PR]2025/02/26 마이페이지 제공자 신청 -김규남✨
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/pages/admin/AdminConvert.js
  funniture-fe/src/pages/admin/AdminLeaver.js
  funniture-fe/src/pages/admin/AdminOwner.js
  funniture-fe/src/pages/admin/AdminUser.js
  funniture-fe/src/pages/admin/adminUser.module.css
  funniture-fe/src/pages/admin/rental.module.css
  funniture-fe/src/pages/user/AppConvert.js
Labels: 📅ToDo📅

#184 🌐✨[PR]2025/02/27 제공자 전환 데이터 화면 출력 - 김규남✨🌐
  funniture-fe/src/apis/AdminAPI.js
  funniture-fe/src/pages/admin/AdminConvert.js
Labels: ✨Feature✨, 📅ToDo📅

#185 :globe_with_meridians:[PR]2025/02/27 제공자 예약조회(탭별, 만료기간별 필터링) - 백&프론트 연결-정은미:globe_with_meridians:
  funniture-fe/src/apis/RentalAPI.js
  funniture-fe/src/pages/owner/OwnerRental.js
  funniture-fe/src/pages/owner/ownerRental.module.css
  funniture-fe/src/pages/user/Orders.js
Labels: ✨Feature✨, 🎨CSS🎨

#188 :sparkles:[PR]2025/02/27 제공자 예약 조회 - 예약진행상태 select-정은미:sparkles:
  funniture-fe/src/layouts/ownerlayout.css
  funniture-fe/src/pages/owner/OwnerRental.js
  funniture-fe/src/pages/owner/ownerRental.module.css
Labels: ✨Feature✨

#190 :sparkles: [PR] 2025/02/27 관심상품 전체 완료 - 정예진 :sparkles:
  funniture-fe/src/apis/FavoriteAPI.js
  funniture-fe/src/assets/icon/empty-heart.svg
  funniture-fe/src/assets/icon/fulll-heart.svg
  funniture-fe/src/assets/images/a.jpg
  funniture-fe/src/assets/images/a1.jpg
  funniture-fe/src/assets/images/a2.jpg
  funniture-fe/src/assets/images/a3.jpg
  funniture-fe/src/assets/images/soldout_label1.png
  funniture-fe/src/assets/images/soldout_label2.png
  funniture-fe/src/pages/common/ListPage.js
  funniture-fe/src/pages/common/ProductDetailPage.js
  funniture-fe/src/pages/common/listpage.css
  funniture-fe/src/pages/common/productDetail.module.css
  funniture-fe/src/pages/login/Singup.js
  funniture-fe/src/pages/user/FavoritesPage.js
  funniture-fe/src/pages/user/Recentproduct.js
  funniture-fe/src/pages/user/favoritesPage.module.css
  funniture-fe/src/pages/user/mypage.css
  funniture-fe/src/redux/modules/FavoriteModule.js
  funniture-fe/src/redux/modules/index.js
Labels: 🔨Refactor🔨, ✨Feature✨, 📅ToDo📅, ✅PR✅, 🎨CSS🎨

#191 ✨[PR]2025/02/27 제공자 전환 신청 / 재신청 연결 - 김규남✨
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/component/Header.js
  funniture-fe/src/pages/user/AppConvert.js
Labels: ✨Feature✨, 📅ToDo📅

#192 :sparkles:[PR]2025/02/27 제공자 예약조회 페이징 처리-정은미:sparkles:
  funniture-fe/src/apis/RentalAPI.js
  funniture-fe/src/component/Pagination.js
  funniture-fe/src/pages/owner/OwnerRental.js
  funniture-fe/src/pages/owner/ownerRental.module.css
Labels: ✨Feature✨

#193 ✨[PR]2025/02/27 제공자 전환 신청 / 관리자 페이지 - 김규남 ✨
  funniture-fe/src/apis/AdminAPI.js
  funniture-fe/src/apis/MemberAPI.js
  funniture-fe/src/component/BtnModal.js
  funniture-fe/src/pages/admin/AdminConvert.js
  funniture-fe/src/pages/user/AppConvert.js
  funniture-fe/src/redux/modules/MemberModule.js
Labels: 📅ToDo📅, ✅PR✅

#198 ✨[PR]2025/02/28 관리자 페이지 탈퇴자에서 유저로 권한 변경 - 김규남✨
  funniture-fe/src/apis/AdminAPI.js
  funniture-fe/src/pages/admin/AdminLeaver.js
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅

#200 💄✨[PR]2025/02/28 관리자 페이지 사용자를 탈퇴 회원으로 전환 / 버튼 css - 김규남✨💄
  funniture-fe/src/apis/AdminAPI.js
  funniture-fe/src/pages/admin/AdminConvert.js
  funniture-fe/src/pages/admin/AdminLeaver.js
  funniture-fe/src/pages/admin/AdminOwner.js
  funniture-fe/src/pages/admin/AdminUser.js
  funniture-fe/src/pages/login/FindPass.js
Labels: ✨Feature✨, 📅ToDo📅, 🎨CSS🎨
